SHOW COLUMNS FROM customers;
SHOW COLUMNS FROM employees;
SHOW COLUMNS FROM offices;
SHOW COLUMNS FROM orderdetails;
SHOW COLUMNS FROM orders;
SHOW COLUMNS FROM payments;
SHOW COLUMNS FROM productlines;
SHOW COLUMNS FROM products;